language: java

sudo: false

services:
- postgresql

jdk:
- oraclejdk8

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH=$HOME/.yarn/bin:$PATH

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - "charlie/node_modules"

before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- psql -c "create user team5 with password 'augsburg123';" -U postgres

script: ./gradlew check

deploy:
  provider: heroku
  api_key:
    secure: vHYA6o6BA/tT+0X400DmPIhdvLIcOPhacgWCwxxv65pvUdoWNeLmYM8wrE/RBSWpZtUdqHVaC4SjX4Wmm0WZd/Xb3baJhBukK3lmmf3xWJd3/1ZcuENfLsMT2LQ1uTS/zDBAnCSUV3tdbaobSt4X9cjURJsFTWrhgVoOzl77wTPh7nQHoKd1kYGdptsPNwR3CkZKS4BN78ofFMv86l3MYUFXl6mUN3Hl1GhGaauvHPnIKY6gAHKp5mGuXvlXfzKYcUzPLNhqDfjqKGkeRyRmLKP3NlRLQ45XPA4w+AGtbLyBk7mHLAa1u3QwFmfF9BCUrJdt3EJVwbdaXIQR21vSIVNklU1BuIc0BKP8OooQskJOD1M+xpb720k8RgizUONSpcnc0Dg4qHOdldB/0B9kOJzn/lpLrymu20b7yjymF7nOIdQSMpfug2jiy4M0RdaPLND1yXrRiss6EQAXknN28k0nI433sZyyLmfBdeBB+XyLktBwx7i0yYBeECVwuqsFymrLxrgNt7pyDhWHkbI0cACilhb9VEpkn+SbfSSGRHuImH3lanrJ8expj952NV71nUuCH4d6xS8xoqKWr0X0YK8dHTVmyG5ule6pXJ2yza3wFYHXa1z3nCQcCtFkAmehLmz2Z/oHZmbelBS6l5SyC6rHjvdmDxEe5lTF7QdsYgc=
  app: charlie-five
  on:
    repo: qw3ry/team5
    branch: master

notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    secure: HOZZ6Ot1bwiOImAI9VAWsh++aZuo6/16B1dqYY1x8YWvf9pyY1cbnAkrj6zo6dtTs2wxyqP6yIyXwI+CmcDRB2eSIzJNloJH2T1D62cX6aEMSlQeCWhlSC0nsXhXUBPPzt7uD9aRiAqwmxsNgEoypHFYaZOAEqHLkFNOA+UqdrDlFulhVcsqxAxxgnBj0INfSyf7nnGCK/i5VxlmUgXM41nYm3M2bi71h2FzndXcwfUFtN1tf6e5CpWwsXFNJHe8+EKPMP6dDQtz5lraNixvj8EqvYAXor9TfjO6GwkQO3eo46AiWA/VHm3+5CI403aPixYXKOFLIslpVzvgQ9TLHJvPM6TopOpxRen+6W2thcrtHLu9Bmyl+mKJpgd5sSSsDY6paAZOkc+LDiRGC4DxkB60rZ1/ujTPNFrIuQzMY5OuICV6XPf3Zcv7CBzyQlrQa2y1YfRJ0rtITGzlZ2SKjHrkKgi0tpMxD0avy4vKB2Yn5WsP6X6pWC5lJcxPVYFBEFoc1QfLJfJj/ewIBp7/rHdKfiuRNfKki9p2LnFRGS1gKWbEPBCfuMhRCmtAsEUxFyMl3Wu8V+nJ1JbFZgBVP+zLVhiVxj7Yp2S/j2Ame66DmSgCKjOz4SRStHAcTYioEtkJWf/aKfV7xn+PZaGqaqrwtMWkCol4fz/nvBLajqE=
    on_success: never
