package de.team5.super_cute.crocodile.model;

import de.team5.super_cute.crocodile.external.C4CProperty;

/**
 * Base Class for all Entities that should be serialized to SAP C4C Objects.
 * Use @C4CProperty to mark as which C4C Attribute a field should be saved.
 */
public abstract class C4CEntity {

  @C4CProperty(name = "ID")
  public String id;

  /**
   * Should not be set in Code, is generated by the C4C Automatically
   */
  @C4CProperty(name = "ObjectID")
  public String objectId;

  /**
   * @return the name of the collection (e.g. "ObjectCollection") in which the Objects of the corresponding Type are saved.
   */
  public abstract String getCollectionName();

  /**
   * @return a default object of the class (convenience for reflection)
   */
  public abstract C4CEntity getEmptyObject();

}
