import { ServiceRequestTarget } from './service-request-target';
import { FeedbackData } from './feedback-data';

export class ServiceRequestData {
  id: string = null; // generated by backend
  name: string = null; // generated by backend
  type: string; // CLEANING or MAINTENANCE
  target: ServiceRequestTarget;
  statusCode: string; //OPEN, IN_PROCESS, CUSTOMER_ACTION, COMPLETED, CLOSED, used in C4C
  dueDate: string;
  completionDate: string = null; // used in C4C
  serviceRequestDescription: string;
  feedback: FeedbackData[];
  priority: string; // FINE, PROBLEMATIC or CRITICAL, like state
}
